# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 06b29ec4b66c7fb9fd729683efc8eb18d4656ce8d35c661af135c60503e2f3bc72b3df353558fad40ea8e1d65a80c25b3ec79944e2ac1573184763d643b1aff0

test:
  secret_key_base: 35f0eaccff9149812df11073ab486743e5db002b3ded3a31d10fe3d06257d17feb90cb9e3d2e1e90c6c028e245da628c84dd2a75dc60e24c68eb59568eefc5ad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
